### ISSUE TITLE
Can't sort by 'Sold' on objkt page

### ISSUE THREAD

**Issue by kylegrover** [hicdex/hicdex-hen-graphql-samples#6]
Random quirk, can't imagine what's causing this honestly. All the other columns sort correctly except the 'Sold' column. The values are all 0 or 1.

https://hicdex.com/objkt?objkt=93229

**Comment by vhf** [comment]
Good catch, thanks!

Fixed in 1ab3201bbdd1ceafd45e1ba7425087912a804eab
